name: dev build

on: workflow_dispatch

env:
  UI_IMAGE_NAME: metaops/kassette-transformer



jobs:
  build:
    runs-on: self-hosted  
    steps:
    - uses: actions/checkout@v3
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}    
    - name: create latest tag if its the main branch
      if:  ${{ env.RELEASE_VERSION == 'main' }}
      run: echo "DOCKER_TAG=latest" >> $GITHUB_ENV  
    - name: create git tag if its the build uses tag
      if:  ${{ env.RELEASE_VERSION != 'main' }}
      run: echo "DOCKER_TAG=${{ env.RELEASE_VERSION }}" >> $GITHUB_ENV  
    - name: configure backend for production
      run: echo "VITE_APP_BACKEND_BASE=http://localhost:8088" > .env
    - name: Build docker image for kassete-transformer
      run:  docker build . --file Dockerfile --tag ${{ env.UI_IMAGE_NAME }}:dev${{ env.DOCKER_TAG }}
    - name: docker login
      run: docker login $DOCKER_REGISTRY -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
    - name: docker push agent
      run: docker push ${{ env.UI_IMAGE_NAME }}:dev${{ env.DOCKER_TAG }}
